.env.sample
src/environment.py
src/fetch/dune.py
src/logger.py
src/main.py
src/post/aws.py
src/sync/app_data.py
src/sync/common.py
src/sync/order_rewards.py

Preparing for deployment on kubernetes we fix a few things:
- using an absolute VOLUME_PATH (instead of relative to the project root)
- configure log level via runtime arguments
- use AWS access keys instead of PROFILE (so we don't have to rely on a credentials existing within the file system).
Integration tests (however they all require A LOT of credentials). You could run the main branch in `dry-run` mode with empty aws credentials (however, there was a subtle bug discovered here while testing that is resolved in a follow up PR #10). 
```sh
python -m src.main --sync-table order_rewards --dry-run True
python -m src.main --sync-table app_data --dry-run True  <--! Running This from scratch takes over an hour!
```

Configuration Final Touches

---

src/post/aws.py
src/sync/app_data.py
tests/integration/test_aws.py

The AppData script takes over an hour to complete (only on the first run). Since the recent changes to AWSClient instantiation, we had to establish the connection at the time the actions are performed. I am not sure if this is the best solution, but something like this will have to be done. All subsequent runs will never take so long.

AWS establish connection for all actions

---

README.md
src/fetch/orderbook.py
src/main.py
src/sql/orderbook/order_rewards.sql
tests/integration/test_fetch_orderbook.py

1. This PR changes the schema of the order rewards table and requires coordination with the Dune team to update it on their end. Since the values are in WEI, to preserve accuracy we extract and store as string type.
2. This PR also introduces a breaking change feature for "hard reset" which empties the AWS buckets and removes the same data from our local storage, before proceeding with the sync script.
This is one part of a bigger change to make limit order fees available in Dune Community sources (so that the slippage query can consume it for solver-rewards).
cc @nlordell 
Tagging also @dsalv (since I have included your github handle in the README and wanted to make sure this is OK with you).
It is nice that we haven't already released this to production (because these kinds of changes …

[order_rewards] Add surplus fee

---

src/models/order_rewards_schema.py
src/sql/orderbook/order_rewards.sql
src/sync/order_rewards.py
tests/integration/test_fetch_orderbook.py
tests/unit/test_order_rewards_schema.py

The schema proposed here is `[order_uid: str | tx_hash: str | solver: str | data ]` where (currently) data takes the following form:
```
Data {
surplus_fee: str (we can make make this nullable, or use zero in place of null)
amount: float
safe_liquidity: boolean (nullable)
}
```
Examples, of this are provided in the unit test.
1. Technically the `solver` column isn't necessary since it can be obtained from the `tx_hash`. Let me know if we think it should be removed.
2. I spoke with Dune today about string types in spark SQL and their answer was as I expected:
> We use decimal(38,0) or just strings for large integers in spark. DuneSQL will provide native support for large integers but it’s not directly available in spark sql
Note that, we will use strings for the `surplus_fee` and cast to …

[Schema] Order Rewards to use JSON field for variable data.

---

src/fetch/ipfs.py
src/models/order_rewards_schema.py
src/sql/orderbook/order_rewards.sql
tests/integration/test_fetch_orderbook.py
tests/unit/test_order_rewards_schema.py

Related to https://github.com/cowprotocol/solver-rewards/pull/157 and this [slack discussion](https://cowservices.slack.com/archives/C036JAGRQ04/p1670575811093429?thread_ts=1670490472.953269&cid=C036JAGRQ04)
we remove safe liquidity field from query and order rewards schema.

Remove Safe Liquidity

---

src/fetch/orderbook.py
src/models/order_rewards_schema.py
src/sql/orderbook/order_rewards.sql
tests/integration/test_fetch_orderbook.py
tests/unit/test_order_rewards_schema.py

For query efficiency reasons, we would need to include block number on the order rewards table in our community sources (this will allow us to join on trades more efficiently). 
⚠️ - this will require coordination with Dune on Redeployment. cc @dsalv
Existing Unit tests which have been adapted.

[Schema] Add block_number to order_rewards

---

requirements/prod.txt
src/main.py
src/post/aws.py
src/scripts/download_file.py
src/scripts/empty_bucket.py
tests/integration/test_aws.py

There is no UI to view and manage files in the AWS buckets, so when we want to peek a file we can `download_file`. Furthermore (and more importantly), the script argument `hard-reset` didn't make sense to include in our deployments since we would only every want to do this once. So instead we provided an independent utility script to `empty_bucket` which should be done (one time) before deploying schema changes.
This was already used recently for deployment of the changes to order rewards made in #23.

Add Utility Scripts (empty_bucket & download_file)

---

README.md
src/main.py

In #25 we removed hard-reset from the main script path but forgot to update the runtime argument configuration.
This removes it 
Try running this script in try run mode (note - this requires a bunch of env vars). Trust me I did it.
```
git push --set-upstream origin hotfix-hardreset
```

[HotFix] Forgotten Instance of hard-reset

---

README.md
src/sql/orderbook/batch_rewards.sql

As part of #27 we implement the Raw Orderbook query that will be used to extract the data to be synced with Dune. The follow up to this PR will implement the python script executing this that is also responsible for transforming it into the JSON files being uploaded to Dune's AWS bucket.
Solvers are expected to change their rewards to the following
```
reward(txHash) = observedQuality - referenceScore
```
where `observedQuality = Surplus + Fee`
Furthermore, the reward per batch is planned to be capped by `[-E, E + executionCosts]  (E = 0.01 ETH)`
This query joins several tables in order to provide all terms required to evaluate the reward (namely surplus, fee, execution_cost, reference_score). `winning_score` is included too which is not really necessary but more for transparency. …

[Batch Rewards] Orderbook Query for Batch Rewards

---

src/fetch/orderbook.py
src/models/batch_rewards_schema.py
src/sql/orderbook/batch_rewards.sql
src/sync/order_rewards.py
tests/integration/test_aws.py
tests/integration/test_fetch_orderbook.py
tests/unit/test_batch_rewards_schema.py

This PR finalizes the DB query based on the progress made in [rewards script](https://github.com/cowprotocol/solver-rewards) -- specifically that query which was finalized [here](https://github.com/cowprotocol/solver-rewards/pull/203)
Its a bit gross that the orderbook query lives in two places (for the time being). At some point we will want to expose this as an API endpoint (on a constrained `block_range`) directly via the orderbook. However, until we have landed on the correct query (sufficient to reproduce solver rewards) we will maintain this externally - in two places.
The tests introduced here are both for the DB extraction result and then the transformation phase to JSON before upload.
Closes #31

[CIP-20] Update Query & Test

---

.github/workflows/pull-request.yaml
src/fetch/postgres.py
src/main.py
src/models/tables.py
src/models/token_imbalance_schema.py
src/sql/warehouse/latest_block.sql
src/sql/warehouse/token_imbalances.sql
src/sync/token_imbalance.py
tests/e2e/test_sync_app_data.py
tests/integration/test_warehouse_fetcher.py
tests/unit/test_token_imbalance_schema.py

Adding `internal_imbalance` sync script, which is basically the same as the orderbook jobs, but reading from a different DB. The query is not overly complicated making a single join to get block numbers.
Note that we wrote a `PostgresFetcher` class to read from this DB (since the OrderbookFetcher reads from two DBs and combines results). More natural approach would be to have a `MultiInstanceDBFetcher` recently introduced in solver-rewards [here](https://github.com/cowprotocol/solver-rewards/pull/200/files#diff-14bc0f308aa5dcfb330f143b5cfe3fe34dd01df48d289adb8b6277d065df3994)
new tests introduced

[Slippage V2] Sync Internal Transfers

---

src/sync/token_imbalance.py

The earliest block where we have solver competition data. Goes back to this transaction (July 19, 2022)
https://etherscan.io/tx/0x044499c2a830890cb0a8ecf9aec6c5621e8310092a58d369cdef726254d3d108
Found via the following query on the production orderbook
```sql
select * from solver_competitions where id = 1;
```

[Slippage] Add genesis_block for internal_imbalances

---

src/models/token_imbalance_schema.py
tests/unit/test_token_imbalance_schema.py

We had an issue with type inference on Dune side. We don't want our large integers being cast to Decimal so we use string.

Use String for Large Numbers

---

src/post/aws.py
tests/integration/test_aws.py

These logs were getting out of control (too many files being printed). WE reduce the log to just the dict keys (which does not grow).

Reduce log message to dict keys instead

---

src/fetch/ipfs.py
src/fetch/orderbook.py

In order to make the diff in https://github.com/cowprotocol/dune-sync/pull/44 easier to digest, we do a small refactoring before. 
We break async content fetching into two methods.

Rework async content fetching

---

src/fetch/ipfs.py
src/fetch/orderbook.py
tests/unit/test_ipfs.py

This change extends the Cid class to support arbitrary prefixes and explicitly makes use of both the OLD and NEW format that we use in https://github.com/cowprotocol/services. 
Because we will need to support both for eternity, the app content fetching is reworked in a way that prioritizes the new format and only attempts the old format when the new one is unavailable.
I believe that we could completely remove support for the old format if all the existing files were migrated to the corresponding CIDs (i.e. those constructed with the new format) -- cc @vkgnosis is this something we plan to do? If we did this, then the changes to be made here would be only a one line change of prefix.
Note this is based on (and blocked by #45)

[AppData] Support for New Format

---

src/post/aws.py

In an effort to supply fewer env vars to our pods, when the image is deployed on AWS, certain session tokens for obtaining credentials are already injected into the runtime environment. 
FYI (@cowprotocol/analytics)
This is an experimental PR made in collaboration with @mateipopa from devops that will be reverted if it does not work out. Alternatively we could deploy a beta version based on this branch and test that out in staging before even merging.

[AWS] Get Credentials from Session

---

src/fetch/ipfs.py
tests/unit/test_ipfs.py

It's possible that in the future some app data content will only be available in the cow protocol backend.
To make the app data indexing work properly in those cases we need to add another fallback to app data fetching.
The new order is:
1. try new format on IPFS
2. try old format on IPFS
3. try any format on the prod backend
4. try any format on the staging backend
* unit test that verifies that content that `fetch_from_backend()` is able to find content that only exists on prod or only exists on prod
* unit test that verifies that hex strings with or without `0x` prefix
* a unit test that verifies that `fetch_many()` is able to fetch app data that only exists in the backend was not possible at the time because such data didn't exist yet

Fetch appdata from backend

---

requirements/prod.txt
src/fetch/ipfs.py

We are currently wasting our pinata credits because we first try to repeatedly fetch the appdata from IPFS when we are currently not even uploading that to IPFS.
Instead we should always try to fetch from our backend first because that's basically free and should have all the useful appdata (nonsense values are not stored there).

Check for appdata in the backend first

---

src/sql/orderbook/order_rewards.sql

We decided to restrict a bit more quotes which can receive rewards to be in line with the original spirit of CIP-27.
This PR would make the data synced to dune consistent with https://github.com/cowprotocol/solver-rewards/pull/328
The additional restrictions are:
- only orders where the amounts are below quoted amounts are eligible
- only orders which are not partially fillable are eligible
Note that the convention for block ranges in this repo is different from the convention in the solver rewards repo. This inconsistency is maybe a bit confusing. But not a problem for any of the queries since this repo is only about syncing data.

Restrict orders which receive quote rewards

---

src/sql/orderbook/order_rewards.sql

This PR addresses issue #62, which was caused by a change in our database. Specifically, the `order_execution` table now only contains entries for limit orders (and NOT market orders).

Fix query that computes quoter and syncs data on Dune

---

requirements/prod.txt

Fix pandas version to 2.1.4 circumvent a `AttributeError: 'Engine' object has no attribute 'cursor'` when querying databases.

Fix pandas version to 2.1.4

---

src/sql/orderbook/batch_rewards.sql
src/sql/orderbook/order_rewards.sql

The cap for volume fees in the current code is based on the assumption that the protocol fee on surplus for sell orders is a fraction of the amount received by the user, i.e., a fraction of the total buy amount. The implementation in the driver is based on the cap being a fraction of the amount sent by the user, i.e., a fraction of the total sell amount. This resulted in an issue due to fees in sell tokens being implicitly converted to buy tokens via the uniform clearing price and not using effective directional prices.
This PR changes the cap to be consistent with the current driver implementation.
This requires re-syncing data to dune.
The code should be changed back in combination with a fix to the driver for rank by surplus since the concept of observed fee has no meaning there.

Fix volume cap for protocol fees

---

src/sql/orderbook/batch_rewards.sql
src/sql/orderbook/order_rewards.sql

Follow up PR on #67 that takes care of volume cap for buy orders.

Fix volume cap for protocol fee for buy orders

---

src/sql/orderbook/latest_block.sql

Dune uploads are broken at the moment due to a change to the `settlements` table in our database. This PR changes the query to be compatible with that change.
Instead of looking at the earliest block without some transaction data in the `settlements` table we now look at the latest block in the `settlement_observations` table.
This should work with both the new and old format of the settlements table.
Tests passed locally.

[Hotfix] Update latest block query

---

tests/unit/test_ipfs.py

This PR removes a failing IPFS test, as reported in issue #60 . Although it would be nice to fix, we don't really have the capacity for this now, and so i am proposing to remove this test so that we don't get constant failures in all the PRs that we are doing at the moment.

Remove failing test

---

requirements/dev.txt

Currently some PRs are failing tests due to black errors. Since there was a new release a few days ago, pinning the version of black might fix them for now.

Pin black version

---

src/sql/orderbook/order_rewards.sql

We currently classify limit orders as in-market based on quoted amounts, see #61. As it turns out, those amounts do not take fees into account for limit orders. Therefore we misclassify some orders whicch are out-of-market as in-market.
This PR changes the classification of in-market orders to be in line with how market orders are created in the frontend: If the quoted amounts are `oq.sell_amount` and `oq.buy_amount` and the estimated fee is `oq.gas_amount * oq.gas_price / oq.sell_price` then a market order sell order would have charged a fee of `oq.gas_amount * oq.gas_price / oq.sell_price` and exchanged the remaining abount `oq.sell_amount - oq.gas_amount * oq.gas_price / oq.sell_price` at the quoted exchange rate `oq.buy_amount / oq.sell_amount` to a buy amount of `(oq.sell_amount - …

In-market classification for fill-or-kill limit orders

---

src/sql/orderbook/batch_rewards.sql

This code change makes the code to compute volume based protocol fees
identical to the code in the solver-rewards repo.
Potentially the implementation is not consistent to what will be done in
the driver. Since volume based fees are not used in production yet this is
not much of an issue for now.
I am also not super sure if we might need different cases for sell and buy orders.
In any case, since we only test those queries in the solver rewards repo
we should make the code consitsant with said repo.

make volume fee code identical to code in solver-rewards repo

---

src/fetch/orderbook.py
src/fetch/postgres.py

This PR addresses issue #72. At the moment the block range is computed using the minimum of the latest finalized block from production and
staging and subtracting `REORG_THRESHOLD = 65`. This was done as a hot fix in #71. One problem with this approach is that having few settlements in staging blocks upload of production data to dune.
This PR changes the behavior to look at the maximum block of the latest finalized blocks from production and staging subtracting
`MAX_PROCESSING_DELAY = 1`. This should leave enough time for the autopilot to process settlements after finalization in staging and production.
For testing we should monitor if there are settlements with missing information on dune compared to our database.

use more optimistic block range for sync

---

src/sql/app_hash_latest_block.sql
src/sql/orderbook/batch_rewards.sql
src/sql/orderbook/latest_block.sql
src/sql/orderbook/order_rewards.sql
src/sql/warehouse/latest_block.sql
src/sql/warehouse/token_imbalances.sql

This PR formats several sql queries of the repo in a nicer way.

Format sql queries

---

src/fetch/orderbook.py
src/sql/orderbook/batch_rewards.sql
tests/integration/test_fetch_orderbook.py

This PR implements changes due to CIP-36. See https://github.com/cowprotocol/solver-rewards/pull/339 for more details.
Fewer changes are required in this repository compared to the solver-rewards repo since some of the reward logic is implemented on dune. The respective dune queries have to be adapted as well.
After merging this a resync for the accounting period starting on 06.02.2024 is required.

Implement CIP-36

---

src/fetch/orderbook.py

Fix dataframe warning

---

src/fetch/orderbook.py
src/sql/orderbook/barn_batch_rewards.sql
src/sql/orderbook/barn_order_rewards.sql

There was a recent staging database change that renamed a column in the fee policies table.
https://github.com/cowprotocol/services/pull/2470
This caused the dune-sycn job to start crashing with the following error:
```
psycopg2.errors.UndefinedColumn: column fp.max_volume_factor does not exist
LINE 93:                     fp.max_volume_factor * os.sell_amount * ...
```
This PR adds a temporary fix, which should be cleaned up this Tuesday as the change moves to prod as well with the upcoming weekly release.

Temporary fix for breaking change in staging database

---

src/sql/orderbook/barn_order_rewards.sql
src/sql/orderbook/prod_order_rewards.sql

I am tempted to say that there is a bug in the order rewards query. Specifically, it seems that the following case might happen:
- we look at all trades executed between a `start_block` and an `end_block` in the trade_hashes table.
- we then pull additional information about these trades, in order to compute protocol fees etc, and these computations start with the `order_surplus` table. But in that table, which contains information from the `settlement_scores` table, we ask that the deadline of the settlements we look into is `end_block`. I think this can cause some information to be lost, because we do a left outer join of the trade_hashes table with everything else, so every trade executed between `start_block` and `end_block` will be included in our result, while not all information …

Add looser block deadline in order rewards query

---

.devcontainer/devcontainer.json

I was a bit hasty merging #100. In order to properly develop using this container, we need 2 more things
1. Install python tooling inside the devcontainer's vscode
2. Install develeopment requirements (the docker container installs prod requirements only) in order to run tests/lints etc

[Trivial] DevContainer improvements

---

src/main.py

VOLUME_PATH and AWS env vars aren't needed anymore for the app_data job and so they shouldn't be required in the environment (cf. https://github.com/cowprotocol/infrastructure/pull/1770/files#diff-6ed79a81a644cd7d10f8cdd1395db1c2371d171337c95f5699db5c906a0b8682R44-R48)
Run `python3 -m src.main --sync-table app_data` without any of the unrelated env vars defined.

[Trivial] remove optional env vars from critical path

---

src/sql/orderbook/barn_batch_rewards.sql
src/sql/orderbook/barn_order_rewards.sql

The script currently produces an error if the same address was used both for staging and prod submissions. This was indeed the case for Copium Capital that tested colocation in staging before we enabled them with the same account in prod (and disabled them in staging at the same time).
The proposed solution is really to bypass the check just for this one occasion, by pretending that the staging submissions of Copium Capital didn't happen from address `0x008300082C3000009e63680088f8c7f4D3ff2E87`,  but instead from the old staging address that the core team controls.

Fix for week where Copium Capital used the same account for both staging and prod

---

src/sql/orderbook/barn_batch_rewards.sql
src/sql/orderbook/prod_batch_rewards.sql

This PR edits a comment that was outdated and led to some confusion about whether the code can properly handle multiple txs from the same environment in the same block (the answer is that it indeed handles them properly).
Identical PR in the solver rewards repo [here](https://github.com/cowprotocol/solver-rewards/pull/402).

[EASY] Fix outdated comment

---

src/fetch/orderbook.py
src/main.py
src/models/tables.py
src/sql/prices.sql
src/sync/__init__.py
src/sync/config.py
src/sync/price_feed.py

This PR adds a simple job that pushes all prices collected in the `prices` table of the analytics db to Dune. It mimics PR #103, and is meant to run as a cronjob. I followed the "legacy method" as there are some concerns about the current way Prefect has been integrated in this repo.
I also prepared this PR in the infra repo. https://github.com/cowprotocol/infrastructure/pull/2217
Note: there are currently not any tests. I saw there are some tests for the app-data sync, so i could try to basically copy-paste those, as i am not sure what's the best way to test this

Sync price feed
